//CARD ACTION
export const ADD_ITEM_TO_CARD = 'ADD_ITEM_TO_CARD';
export const DELETE_ITEM_TO_CARD = 'DELETE_ITEM_TO_CARD';
export const ITEM_IS_SELECTED = 'ITEM_IS_SELECTED';
export const ADD_TOTAL_PRICE = 'ADD_TOTAL_PRICE';
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL= 'GET_PRODUCT_FAIL';
export const UPLOAD_CART_PRODUCT_LOADING = 'UPLOAD_CART_PRODUCT_LOADING';
export const UPLOAD_CART_PRODUCT_SUCCESS = 'UPLOAD_CART_PRODUCT_SUCCESS';
export const UPLOAD_CART_PRODUCT_FAIL = 'UPLOAD_CART_PRODUCT_FAIL';
// //LOGIN ACTION
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';

